# Generated by Django 3.2.5 on 2021-12-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.IntegerField()),
                ('register_email', models.EmailField(max_length=254)),
                ('register_name', models.CharField(max_length=64)),
                ('register_choice', models.CharField(max_length=64)),
            ],
        ),
    ]
