# Generated by Django 3.2.5 on 2021-12-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='register_choice',
            new_name='program',
        ),
    ]
