# Generated by Django 3.2.5 on 2021-12-29 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_is_completed_student_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='ombada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Ahmed', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='occupation',
            field=models.CharField(default='Product Manager', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(default='Mining', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='Khartoum', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(default='UOFK', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
    ]
