# Generated by Django 4.0 on 2022-01-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_enroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='transation_id',
            field=models.PositiveBigIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.program')),
            ],
        ),
    ]
