# Generated by Django 4.0 on 2022-01-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_registration_is_enroll_registration_is_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.batch'),
            preserve_default=False,
        ),
    ]
