# Generated by Django 4.0 on 2022-01-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_batch_number_registration_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transation_id',
            field=models.PositiveBigIntegerField(default=1, null=True),
        ),
    ]
