# Generated by Django 3.2.5 on 2021-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_program_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default='old', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='old', max_length=64),
        ),
    ]
