# Generated by Django 4.0 on 2022-01-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_registration_transation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='transation_id',
            new_name='transaction_id',
        ),
    ]
