# Generated by Django 3.2.5 on 2021-12-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20211228_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='name_english',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='name_english',
        ),
        migrations.AddField(
            model_name='program',
            name='name_arabic',
            field=models.CharField(default='قديم', max_length=64),
        ),
        migrations.AddField(
            model_name='track',
            name='name_arabic',
            field=models.CharField(default='قديم', max_length=64),
        ),
    ]
