# Generated by Django 4.0 on 2022-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_rename_transation_id_registration_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
