# Generated by Django 4.0 on 2022-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_registration_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(default='IRL', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='name_arabic',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_english',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='track',
            name='name_arabic',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='track',
            name='name_english',
            field=models.CharField(max_length=64),
        ),
    ]
