# Generated by Django 4.0 on 2022-01-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_program_code_alter_program_name_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.batch'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.program'),
        ),
    ]
