name: Django CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: actions/deploy-django@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        aws-region: us-east-2
        instance-ids: ${{ secrets.INSTANCE_ID  }}
        comment: configure the AWS credentials
        working-directory: /home/ubuntu/codesudan
    - name: Deploy Django
      run:
        sudo git pull origin master
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py collectstatic
        sudo service apache2 restart

